### ISSUE TITLE
Do you have solution for calculation data?

### ISSUE THREAD

**Issue by JJ306** [Coul33t/NeuronSDKTest#2]

**Comment by Coul33t** [comment]
Hello,

it would basically be the same as BvhFrameDataReceived, but you would have to change the BvhExport function to fit the data received (look into the Perception Neuron's SDK doc [here](https://neuronmocap.com/content/neurondatareader-sdk),page 5 & 6, for informations about what data is inside the calculation data). If you can't do it by yourself, I'll probably give it a try in a few weeks/months when I'll have more time to work on it.

Cheers
