### ISSUE TITLE
request: about licence

### ISSUE THREAD

**Issue by doge-gif** [Coul33t/NeuronSDKTest#4]
Hello, I really appreciate your work and want to make a program using some of your code.
Under what license are you publishing this program? Thank you.

**Comment by Coul33t** [comment]
Hey,

Thanks for pointing out that the repo lacked a license! It's done now, I chose a MIT license, so feel free to use it as you want. Don't hesitate to link my repo or my github profile, but don't feel forced to do so!

Cheers

**Comment by doge-gif** [comment]
Thanks!
